eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/
server: 
  port: 8080
spring: 
  application: 
    name: api-gateway
  cloud: 
    loadbalancer:
      ribbon:
        enabled: false #Because @FeignClient does load balancing as well
    gateway: 
      discovery:
        locator:
          enabled: true
      routes: 
        - id: item-service
          predicates: 
            - Path= /items/**
          uri: lb://item-service
        - id: order-service
          uri: lb://order-service
          predicates: 
            - Path= /orders/**
          filters:
           - name: Logging
             args:
                 baseMessage: My Custom Message
                 preLogger: true
                 postLogger: true
        - id: order-service
          uri: lb://order-service
          predicates: 
            - Path= /order-service/**
          filters:
            - RewritePath=/order-service/, /orders/
            