spring.application.name: order-service
server.port: 8088
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring.datasource.name: orderdb
spring.jpa.hibernate.ddl-auto: create
spring.jpa.show-sql: true
spring.h2.console.enabled: true

resilience4j.circuitbreaker:
    instances:
        orderService:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 20
            waitDurationInOpenState: 50s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10